[package]
name = "rust-example"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
dlopen2 = "0.7.0"
serde = { version = "1.0.204", features = ["derive"] }
struct-field-names-as-array = "0.3.0"
serde_json = "1.0.120"